### ISSUE TITLE
Blog down?

### ISSUE THREAD

**Issue by fernand0** [armoredcode/armoredcode.github.io#1]
Hello,

Is it a temporary failure or you have moved to another site/proyects?

Best regards,

--
Fernando Tricas

**Comment by thesp0nge** [comment]
Hi @fernand0 thank you for the alert.

Just a temporary failure due to DNS configuration.
I just modified A records and should be fixed very shortly.

(after a while I blogged only in Italian, I'm planning to start blogging again also here)

**Comment by fernand0** [comment]
Thanks!

**Comment by thesp0nge** [comment]
Fixed :+1:
